package kalkulacka;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PavelW7
 */
public class Hlavni_okno extends javax.swing.JFrame {

    
    double hruba;
    double vysledek;
    double superhruba;
    double pojisteni_za_zamestnance;
    double pojisteni_zamestnavatele;
    double zaokrouhlene;
    double zaloha_na_dan;
    double sleva_na_poplatnika;
    double cista_mzda;
    int jednodite = 1117;
    int druhedite = 1617;
    int tretidite = 2017;
    int pocet_deti = 0;
    
    public Hlavni_okno() {
        initComponents();
        
  
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextHruba = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonVypocti = new javax.swing.JButton();
        jTextPocet_deti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelCista_mzda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextVystup = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zadejte hrubou mzdu");

        jButtonVypocti.setText("Vypočti");
        jButtonVypocti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVypoctiActionPerformed(evt);
            }
        });

        jLabel2.setText("Počet dětí");

        jLabelCista_mzda.setText("Čistá mzda:");

        jTextVystup.setColumns(20);
        jTextVystup.setRows(5);
        jScrollPane1.setViewportView(jTextVystup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelCista_mzda, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVypocti))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextHruba)
                            .addComponent(jTextPocet_deti))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHruba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPocet_deti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVypocti)
                    .addComponent(jLabelCista_mzda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVypoctiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVypoctiActionPerformed
        
        if (jTextHruba.getText().length()==0) {
            jTextVystup.setText("Zadejte hrubou mzdu");
        }else{
        
        
        hruba=Double.parseDouble(jTextHruba.getText());
        if (hruba < 11000) {
            jTextVystup.setText("Minimální mzda je 11000\nopravte vstup");
        }else{
            
        
        
        if (jTextPocet_deti.getText().length()==0) jTextPocet_deti.setText("0");
        
        pocet_deti=Integer.parseInt(jTextPocet_deti.getText());
        
        
        pojisteni_za_zamestnance = (hruba * 0.065) + (hruba * 0.045);
        pojisteni_zamestnavatele = (hruba * 0.25) + (hruba * 0.09);
        superhruba = (hruba + pojisteni_zamestnavatele);
        zaokrouhlene = ((superhruba + 99) / 100);
        int vysledek1 = (int) zaokrouhlene*100;
        zaloha_na_dan = vysledek1 * 0.15;
        sleva_na_poplatnika = zaloha_na_dan - 2070;
        cista_mzda = hruba - pojisteni_za_zamestnance - sleva_na_poplatnika;
       
        if (pocet_deti == 1){
            cista_mzda = cista_mzda + jednodite;
        }
        if (pocet_deti == 2){
            cista_mzda = cista_mzda + jednodite + druhedite;
        }
        if (pocet_deti >= 3){
            cista_mzda = cista_mzda + jednodite + druhedite + tretidite;
        }
          
             
       jTextVystup.setText("Čista mzda: "+cista_mzda+"Kč\nSuper Hrubá mzda:  "
                +superhruba+"Kč\nZáklad pro výpočet zálohy na daň:  "
                +vysledek1+"Kč\nSociální a zdravotní pojištení (zaměstnanec):  "
                +pojisteni_za_zamestnance+"Kč\nSociální a zdravotní pojištení (zaměstnavatel):  "
                +pojisteni_zamestnavatele+"Kč");
                
        }
        }        
    }//GEN-LAST:event_jButtonVypoctiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hlavni_okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hlavni_okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hlavni_okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hlavni_okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hlavni_okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVypocti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCista_mzda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextHruba;
    private javax.swing.JTextField jTextPocet_deti;
    private javax.swing.JTextArea jTextVystup;
    // End of variables declaration//GEN-END:variables
}
